esphome:
  name: guitar
  platform: ESP8266
  board: d1_mini
  includes:
    - guitar.h

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  password: ""

wifi:
  ssid: "Ziggo0590921"
  password: "xvvt3DtLdyqh"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Guitar Fallback Hotspot"
    password: "UTxTJ7mHKvWn"

captive_portal:

i2c:
  scan: false

text_sensor:
- platform: custom
  lambda: |-
    auto my_custom_sensor = new GuitarComponent();
    App.register_component(my_custom_sensor);
    return {my_custom_sensor};

  text_sensors:
    name: "Guitar ID"
