esphome:
  name: guitar
  platform: ESP8266
  board: d1_mini
  includes:
    - guitar.h

# Enable logging
logger:

i2c:
  scan: false

text_sensor:
- platform: custom
  lambda: |-
    auto my_custom_sensor = new GuitarComponent();
    App.register_component(my_custom_sensor);
    return {my_custom_sensor};

  text_sensors:
    name: "Guitar ID"
